# .github/workflows/main.yaml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Main Flow
        run: |
          echo "This is main flow"
          date
